package tuttifrutti.utils;

public enum PushType {
	ROUND_RESULT,
	MATCH_RESULT,
	PUBLIC_MATCH_READY,
	PRIVATE_MATCH_READY,
	MATCH_REJECTED,
	MATCH_REJECTED_BY_PLAYER,
	MATCH_EXPIRED,
	MATCH_EXPIRED_FOR_PLAYER,
	BPMBPT;
}
